#include <stdio.h>

/**
 * main - fibonacci seq generated by adding 2 prev num
 *
 * Return: 0
 */

int main(void)
{
	int sum_of_even_num = 0;
	int u = 1;
	int v;
	int sum = 1;

	for (v = 1; v < 4000000; )
	{
		sum = u + v;
		u = v;
		v = sum;

		if ((sum <= 4000000) && (sum % 2 == 0))
			sum_of_even_num += sum;
	}
	printf("%d\n", sum_of_even_num);

	return (0);
}
